
Cholesky Decomposition
```{r}
library(ggplot2)
#establish variance-covariance matrix of bivariate gaussian
sigma = rbind(c(1.0, 0.9),c(0.9,1.0))

#perform cholesky decomposition to get matrix A
A = t(chol(sigma))

#set the mean vector of r length for the bivariate gaussian
mu = c(0,0)
n = 1000

#populate Z matrix of n standard Gaussian distributions
Z = matrix(0, nrow = 2, ncol = n)
for (i in 1:n){
  norms = rnorm(length(mu))
  Z[1,i] = norms[1]
  Z[2,i] = norms[2]
}

#simulate bivariate Gaussian
X = (A %*% Z) + mu
(nrow(X))
(ncol(X))

#name vectors
xdim = X[1,]
ydim = X[2,]

#simulate sample correlation - 100 points
corrs = rep(0, 100)
first = 1
j = 1
for (i in 1:1000){
  if (i %% 10 == 0){
    x = xdim[first:i]
    y = ydim[first:i]
    corrs[j] = cor(x, y)
    
    j = j + 1
    first = i
  }
}

#visualize distribution
df4 = data.frame(xdim, ydim)
dfc = data.frame(corrs)
ggplot(df4, aes(x=xdim)) + geom_histogram(col = 'black', fill = 'lightblue',) + labs(title = "Cholesky Decomposition Bivariate Gaussian Sampling Distribution", x = "Value Sampled", y = "Count")
ggplot(df4, aes(x = xdim, y = ydim)) + geom_point(col = "black") + labs(title = "2D Scatterplot of Cholesky Decomposition Bivariate Gaussian Distribution", x = "x", y = "y")
ggplot(dfc, aes(x=corrs)) + geom_histogram(col = 'black', fill = 'lightgreen',) + labs(title = "Cholesky Decomposition Sample Correlation", x = "Correlation", y = "Count")
(cor(xdim, ydim))
```

The Gibbs Sampler
```{r}
#set up conditional distribution for p(x|y)
px_given_y = function(y, mu, sigma){
  m = mu[1] + sigma[2,1] / sigma[1,1] * (y - mu[2])
  s = sigma[1,1] - sigma[2,1] / sigma[2,2] * sigma[2,1]
  return (rnorm(1, mean = m, sd = s))
}

#set up conditional distribution for p(y|x)
py_given_x = function(x, mu, sigma){
  m = mu[2] + sigma[1,2] / sigma[2,2] * (x - mu[1])
  s = sigma[2,2] - sigma[1,2] / sigma[1,1] * sigma[1,2]
  return (rnorm(1, mean = m, sd = s))
}

#set mean, sample size, and variance-covariance matrix for bivariate gaussian
mus = c(0,0)
sigma = rbind(c(1.0, 0.9),c(0.9,1.0))
n = 5000

#initialize sample list in 2 dimensions
samples_x = rep(0, n)
samples_y = rep(0, n)

#initialize first y as mu and begin iterations
y = mu[2]
for (i in 1:n){
  x = px_given_y(y, mus, sigma)
  y = py_given_x(x, mus, sigma)
  samples_x[i] = x
  samples_y[i] = y
}

#set burn in number
burn = 4000
bsamples_x = samples_x[(burn + 1): length(samples_x)]
bsamples_y = samples_y[(burn + 1): length(samples_y)]

#simulate sample correlation - 100 points
gs_corrs = rep(0, 100)
first = 1
j = 1
for (i in 1:1000){
  if (i %% 10 == 0){
    x = bsamples_x[first:i]
    y = bsamples_y[first:i]
    gs_corrs[j] = cor(x, y)
    j = j + 1
    first = i
  }
}


#visualize
df5 = data.frame(bsamples_x, bsamples_y)
dfgs = data.frame(gs_corrs)
ggplot(df5, aes(x=bsamples_x)) + geom_histogram(col = 'black', fill = 'lightblue',) + labs(title = "Gibbs Sampling Bivariate Gaussian Distribution", x = "Value Sampled", y = "Count")
ggplot(df5, aes(x = bsamples_x, y = bsamples_y)) + geom_point(col = "black") + labs(title = "2D Scatterplot of Gibbs Sampling Bivariate Gaussian Distribution", x = "x", y = "y")
ggplot(dfgs, aes(x=gs_corrs)) + geom_histogram(col = 'black', fill = 'lightgreen',) + labs(title = "Gibbs Sampling Sample Correlation", x = "Correlation", y = "Count")
(cor(bsamples_x, bsamples_y))


```




